# line length https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md013
MD013: false

# punctuation in headings
MD026: false

# duplicated headers - in changelog they can be duplicated
MD024:
  siblings_only: true
